### ISSUE TITLE
Error when updating description

### ISSUE THREAD

**Issue by adripo** [bemble/sync-readme#2]
Hi, I was trying to update the Docker Hub description by setting:

```
- uses: bemble/sync-readme@v1.0.0
  with:
    pass: ${{ secrets.DOCKER_PASS }}
    description: true
```

But I get this error:

```
Syncing ./README.md to ***/…	
	ERR: Unable to update description on Docker Hub
{"detail": "access is forbidden with a JWT issued from a personal access token"}
```

How can I solve the issue?
